### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by michaelb-01** [wojtkowiak/meteor-desktop#12]
Following the quickstart I ran:

meteor --mobile-server=127.0.0.1:3000

This gave me the following error:

/path/to/my/app/.meteor/local/build/programs/server/boot.js:348
}).run();

Error: Cannot find module '../core-js/symbol/iterator'

Any idea how to resolve this? Thanks

**Comment by lorenzogm** [comment]
I got this error yesterday. I was using Meteor 1.4.2 and I had to downgrade Meteor to 1.4.1. Then, if it is not working yet, make sure that the 'meteor' command works.

My 'meteor' wasn't working, so something in `node_modules` and/or `.desktop` was corrupted. I made `meteor` working again (but now with 1.4.1) removing `node_modules`, `.desktop` and `meteor-desktop` from `packages.json`.

Finally the mobile server is working with 1.4.1, but `meteor-desktop` should be fixed somehow for 1.4.2.

**Comment by wojtkowiak** [comment]
This does not seem to be related to `meteor-desktop`. 
This error seems like something that might be thrown if you do not have `babel-runtime` added but that applies to [1.4.2.1](https://github.com/meteor/meteor/blob/devel/History.md#v1421) only.

@michaelb-01, @lorenzogm please check a clear project without `meteor-desktop` added to confirm the download meteor version works fine standalone. If the problems happens only after adding this package I will investigate this further.

**Comment by wojtkowiak** [comment]
If the problem persists in a project without `meteor-desktop` then it will be best if you will submit this as a `meteor` issue.

**Comment by wojtkowiak** [comment]
Can I close this?
